CXX=/usr/local/opt/llvm/bin/clang++
CXXFLAGS=-Wall -Wextra -Wno-deprecated-declarations -O0 -fno-rtti -fno-exceptions -march=native -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -g -std=c++14 -stdlib=libc++ -MMD
#CXXFLAGS=-Wall -Wextra -Wno-deprecated-declarations -O3 -fno-rtti -fno-exceptions -march=native -std=c++14 -stdlib=libc++ -MMD

.PHONY: clean regen all

all: regen report.docx report.html report.pdf

regen: Bugs
	awk '{ print } /^# AUTOGENERATED/ { exit }' Makefile > Makefile.new
	cat src/*.d >> Makefile.new
	mv -f Makefile.new Makefile

clean:
	-rm -f Bugs
	-find . \( -name '*.o' -o -name '*.d' \) -delete

Bugs: src/Actor.o src/GameController.o src/GameWorld.o src/main.o src/StudentWorld.o
	$(CXX) $(CXXFLAGS) -framework OpenGL $^ /opt/X11/lib/libglut.dylib -o $@

report.docx: report.txt
	pandoc --toc --smart --standalone --from markdown+inline_code_attributes -o $@ $<

report.html: report.txt
	pandoc --toc --smart --standalone --from markdown+inline_code_attributes -o $@ $<

report.pdf: report.txt
	pandoc --toc --smart --standalone --variable=geometry:letterpaper,margin=1in --from markdown+inline_code_attributes -o $@ $<

# AUTOGENERATED DEPENDENCIES BELOW
src/Actor.o: src/Actor.cpp src/Actor.h src/Compiler.h src/GameConstants.h \
  src/GraphObject.h src/SpriteManager.h src/freeglut.h \
  src/freeglut_std.h src/freeglut_ext.h src/StudentWorld.h src/Field.h \
  src/GameWorld.h
src/GameController.o: src/GameController.cpp src/freeglut.h \
  src/freeglut_std.h src/freeglut_ext.h src/GameController.h \
  src/SpriteManager.h src/GameConstants.h src/GameWorld.h \
  src/GraphObject.h src/SoundFX.h
src/GameWorld.o: src/GameWorld.cpp src/GameWorld.h src/GameConstants.h \
  src/GameController.h src/SpriteManager.h src/freeglut.h \
  src/freeglut_std.h src/freeglut_ext.h
src/StudentWorld.o: src/StudentWorld.cpp src/StudentWorld.h \
  src/Compiler.h src/GameConstants.h src/Field.h src/GameWorld.h \
  src/Actor.h src/GraphObject.h src/SpriteManager.h src/freeglut.h \
  src/freeglut_std.h src/freeglut_ext.h
src/main.o: src/main.cpp src/GameController.h src/SpriteManager.h \
  src/freeglut.h src/freeglut_std.h src/freeglut_ext.h \
  src/GameConstants.h
